---
# tasks file for ocp4 cluster nodes configuration

# Wait at least 30m for node connection
- name: Check connection
  wait_for_connection:
    delay: 15
    connect_timeout: 15
    timeout: "{{ node_connection_timeout }}"

- name: Configure node
  shell: |
    if lsmod|grep -q 'ibmveth'; then
      sudo sysctl -w net.ipv4.route.min_pmtu=1450;
      sudo sysctl -w net.ipv4.ip_no_pmtu_disc=1;
      echo 'net.ipv4.route.min_pmtu = 1450' | sudo tee --append /etc/sysctl.d/88-sysctl.conf > /dev/null;
      echo 'net.ipv4.ip_no_pmtu_disc = 1' | sudo tee --append /etc/sysctl.d/88-sysctl.conf > /dev/null;
    fi

- name: kernel configuration
  shell: | 
    sudo rpm-ostree kargs --append=rd.multipath=default
    sudo rpm-ostree kargs --append=root=/dev/disk/by-label/dm-mpath-root
    sudo rpm-ostree kargs --append=rw
   # sudo reboot                        

- name: Reboot a host and wait for it to return
  tasks:
    - shell: shutdown -r now
    - pause: seconds=30
    - local_action: shell ansible -u {{ ansible_user_id }} -m ping {{ inventory_hostname }}
      register: result
      until: result.rc == 0
      retries: 30
      delay: 10
    - shell: uptime
    
#- name: Wait for server to restart
 # local_action:
  #  module: wait_for
   #  host={{ inventory_hostname }}
    # port=22
     #delay=1
     #timeout=300
